export const CollegeName = [
  "Indian Institute of Technology Madras (IIT-M)",
  "Anna University, Chennai",
  "College of Engineering, Guindy (CEG)",
  "Madras Institute of Technology (MIT), Chromepet",
  "PSG College of Technology, Coimbatore",
  "Coimbatore Institute of Technology (CIT)",
  "Sri Sivasubramaniya Nadar College of Engineering (SSN)",
  "Thiagarajar College of Engineering (TCE), Madurai",
  "National Institute of Technology, Tiruchirappalli (NIT-Trichy)",
  "Vellore Institute of Technology (VIT), Vellore",
  "SRM Institute of Science and Technology, Kattankulathur",
  "Sathyabama Institute of Science and Technology",
  "Sri Krishna College of Engineering and Technology (SKCET)",
  "Rajalakshmi Engineering College (REC)",
  "Velammal Engineering College, Chennai",
  "Kumaraguru College of Technology (KCT), Coimbatore",
  "Government College of Technology (GCT), Coimbatore",
  "Karunya Institute of Technology and Sciences, Coimbatore",
  "Hindustan Institute of Technology & Science",
  "Vels Institute of Science, Technology & Advanced Studies (VISTAS)",
  "St. Joseph's College of Engineering, Chennai",
  "Saveetha Engineering College",
  "R.M.K. Engineering College",
  "R.M.D. Engineering College",
  "Panimalar Engineering College",
  "Panimalar Institute of Technology",
  "Mepco Schlenk Engineering College, Sivakasi",
  "Bannari Amman Institute of Technology, Erode",
  "Kongu Engineering College (KEC), Erode",
  "Shanmugha Arts, Science, Technology & Research Academy (SASTRA), Thanjavur",
  "Periyar Maniammai Institute of Science & Technology",
  "Government College of Engineering, Salem",
  "Government College of Engineering, Bargur",
  "Government College of Engineering, Tirunelveli",
  "Government College of Engineering, Thanjavur",
  "Loyola-ICAM College of Engineering and Technology (LICET), Chennai",
  "Jeppiaar Engineering College, Chennai",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science & Technology",
  "Bharath Institute of Higher Education & Research (BIHER)",
  "Adhiyamaan College of Engineering, Hosur",
  "Sri Sai Ram Engineering College, Chennai",
  "Sri Venkateswara College of Engineering, Sriperumbudur",
  "Alpha College of Engineering",
  "Dhanalakshmi College of Engineering",
  "KCG College of Technology",
  "Meenakshi Sundararajan Engineering College",
  "Easwari Engineering College",
  "Jerusalem College of Engineering",
  "Agni College of Technology",
  "Anna University Regional Campus, Madurai",
  "Anna University Regional Campus, Coimbatore",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",

  "National Institute of Technology Tiruchirappalli",
  "National Institute of Technology Surathkal",
  "National Institute of Technology Warangal",
  "National Institute of Technology Calicut",
  "National Institute of Technology Rourkela",
  "National Institute of Technology Jaipur",
  "National Institute of Technology Jalandhar",
  "National Institute of Technology Nagpur",

  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "IIIT Gwalior",
  "IIIT Allahabad",

  "Anna University",
  "Vellore Institute of Technology (VIT), Vellore",
  "SRM Institute of Science and Technology",
  "Amrita Vishwa Vidyapeetham",
  "SASTRA University",
  "PSG College of Technology",
  "College of Engineering Guindy",

  "Delhi University",
  "Hansraj College",
  "Hindu College",
  "Kirori Mal College",
  "Ramjas College",
  "Miranda House",
  "Lady Shri Ram College",

  "Jadavpur University",
  "University of Calcutta",
  "IEM Kolkata",
  "Heritage Institute of Technology",

  "Mumbai University",
  "St. Xavier’s College Mumbai",
  "KJ Somaiya College",
  "SP Jain Institute",

  "Osmania University",
  "JNTU Hyderabad",
  "CBIT Hyderabad",
  "VNR VJIET",

  "Savitribai Phule Pune University",
  "COEP Pune",
  "VIT Pune",
  "Bharati Vidyapeeth Pune",

  "Gujarat Technological University",
  "DAIICT",
  "Nirma University",

  "Manipal Institute of Technology",
  "Christ University",
  "RV College of Engineering",
  "PES University",
  "MS Ramaiah Institute of Technology",

  "Punjab University",
  "Thapar Institute",
  "Chandigarh University",

  "BIT Mesra",
  "Ranchi University",

  "IIT BHU",
  "IIT ISM Dhanbad",
  "Aligarh Muslim University",

  "Allahabad University",
  "Banaras Hindu University (BHU)",

  "IIT Indore",
  "IIT Gandhinagar",
  "IIT Bhubaneswar",
  "IIT Mandi",
  "IIT Patna",
  "IIT Ropar",
  "IIT Jodhpur",
  "IIT Palakkad",
  "IIT Goa",
  "IIT Jammu",
  "IIT Tirupati",

  "NIT Hamirpur",
  "NIT Srinagar",
  "NIT Raipur",
  "NIT Patna",
  "NIT Arunachal",
  "NIT Meghalaya",
  "NIT Goa",

  "Guru Gobind Singh Indraprastha University",
  "Jamia Millia Islamia",
  "IGNOU",
  "Jawaharlal Nehru University (JNU)",

  "Loyola College, Chennai",
  "Madras Christian College",
  "Bishop Heber College",
  "Stella Maris College",

  "Christ College, Bangalore",
  "Mount Carmel College",

  "St. Xavier’s College Ahmedabad",
  "St. Xavier’s College Kolkata",
  "St. Xavier’s College Jaipur",
  "Other",
];
