export const degreeOptions = [
  { value: "BE", label: "BE" },
  { value: "BTech", label: "B.Tech" },
  { value: "BSc", label: "B.Sc" },
  { value: "BCA", label: "BCA" },
  { value: "BCom", label: "B.Com" },
  { value: "BA", label: "BA" },
  { value: "ME", label: "ME" },
  { value: "MTech", label: "M.Tech" },
  { value: "MSc", label: "M.Sc" },
  { value: "MCA", label: "MCA" },
  { value: "MCom", label: "M.Com" },
  { value: "MA", label: "MA" },
  { value: "MBA", label: "MBA" },
  { value: "BBA", label: "BBA" },
  { value: "BBM", label: "BBM" },
  { value: "PhD", label: "PhD" },
  { value: "MBBS", label: "MBBS" },
  { value: "Nursing", label: "Nursing" },
  { value: "BDS", label: "BDS" },
];
